### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [cement-hools/Auth_sprint_1#49]
Добрый день! Отлично! Работа на уровне!

Предложения по доработке:

1. Выдача истории входов пользователя должна быть с пагинацией, там через 2-3 месяца будут выдаваться сотни записей.
2. Молодцы, что написали тесты, но их маловато. В задании было: "каждый ответ каждой ручки API и важная бизнес-логика тщательно проверены". Кроме того, можно также тестить на 400 ошибки. Засылаем неверные данные и проверяем что они не проходят и получаем 400. Ну и все роуты апи желательно покрыть тестами
3. В конфиге nginx лучше отключить показ версий для клиента в целях безопасности `server_tokens off;` (как во 2 спринте)
4. Существуют различные паттерны проектирования архитектуры, такие как MVC, MVP и тд (https://habr.com/ru/post/215605/). В общем их суть состоит в том, чтобы отделять бизнес логику от логики представления.
В нашем случае, у нас в роутах (представление) содержится бизнес логика. И если мы, например, захотим ее переиспользовать (например добавить новый роут с похожим функционалом), то нам придется переписывать старые роуты, чтобы избежать DRY (https://web-creator.ru/articles/dry). Поэтому необходимо сразу всю бизнес логику выделять в отдельные модули/классы/функции, чтобы потом можно было удобно ими пользоваться. В роутах мы этими модулями/классами/функциями просто пользуемся и вызываем
5. Я просмотрел код и не нашел системы управления миграциями БД. А скорее такая штука понадобится, так как сервис будет дорабатываться уже в процессе эксплуатации. Посмотрите например [alembic](https://pypi.org/project/alembic/)
6. В [моделях](https://github.com/cement-hools/Auth_sprint_1/blob/main/src/app/db/models/user.py#L70) лучше стараться указывать максимальную длину в полях String. Это позволяет оптимизировать расход ресурсов и защищает от случаев, когда в такие поля пытаются вставить огромные тексты. Если вам точно нужно не ограничивать длину строки, то лучше использовать поле Text
7. В [логгировании](https://github.com/cement-hools/Auth_sprint_1/blob/main/src/app/api/v1/utils.py#L22) не стоит использовать f-string,.format() , а делать через printf-style примерно так - logging.info("message %s", param)
printf-style строка не форматируется до самого последнего момента. То есть если использовать f-string, то все вычисления по формированию строки происходят сразу, а если использовать %s и параметры, то только непосредственно перед выводом данных. А если например level handler будет в конфиге поставлен в critical, то этот лог никуда не отправится, а значит опять же строка форматироваться не будет.
https://okomestudio.net/biboroku/2020/04/on-lazy-logging-evaluation/

**Comment by BigDeepBlue** [comment]
Добрый день! Просмотрел код но так и не нашел систему управления миграциями.
Укажите пожалуйста в ридми где посмотреть.
Не будем считать эту попытку сдать. Следующая будет вторая.

**Comment by cement-hools** [comment]
> Добрый день! Просмотрел код но так и не нашел систему управления миграциями.
> Укажите пожалуйста в ридми где посмотреть.
> Не будем считать эту попытку сдать. Следующая будет вторая.

Подумал рекомендательный характер. Сделаем

**Comment by andrey-lepekhin** [comment]
Auth_sprint_1 сдали еще пару недель назад
