### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [cement-hools/Auth_sprint_1#79]
Ребята, вы большие молодцы!
У меня несколько предложений по доработке:
1.  [Этот импорт](https://github.com/cement-hools/Auth_sprint_1/blob/main/flask/app/services/oauth.py#L10) не используется. В других местах тоже находил. 
2. Имена провайдеров yandex/google лучше поместить в enum. Работа с литералами - всегда не очень хорошая практика. Далее с развитием проекта может возникнуть необходимость их использовать в коде. Работа с enum, как минимум, избавит нас от опасности опечатки.
3. В задании по rate limit было "реализуйте алгоритм Leaky bucket или Token bucket, используя Redis для синхронизации реплик". У вас я нашел только rate limit на уровне nginx. Если я не уведел реализацию с redis - укажите в ридми где можно найти. А если не сделали, то давайте реализуем. Можно воспользоваться https://flask-limiter.readthedocs.io/en/stable/
4. Предлагаю ввести параметр в конфиге, чтобы можно было отключать [телеметрию](https://github.com/cement-hools/Auth_sprint_1/blob/main/flask/app/__init__.py#L50). Ведь, например, в тестах или на dev-стенде она вам вряд ли понадобится. А имея специальный параметр в конфиге, вы сможете легко включать/подключать телеметрию, когда это необходимо.

**Comment by andrey-lepekhin** [comment]
(Всё поправили)
